Create a QUESTIONS.md file for mentors
foundersandcoders/testing-tdd-intro pull request #2
Opened 2018-03-14 17:55 UTC by MynahMarie

These questions are for mentors to use as a guide in order to help futre students solidify their understanding of testing and TDD as well as to try and sensitize them to the importance of testing.

Relates #1

2019-02-15 15:16 UTC, zurda commented
@MynahMarie I've reviewed this, and it looks great. Do you happen to know who can approve this? We're preparing week 2 for FAC-16, and I'd love to get this merged

2019-02-16 12:46 UTC, oliverjam commented
@zurda I can approve it. I've got a couple of typos/phrasing changes to the PR—do you want to make the edits? If it's easier we can merge and then update after

2019-02-16 12:50 UTC, oliverjam requested changes

2019-02-16 12:50 UTC, oliverjam commented on QUESTIONS.md
> +### How do we call the process of testing small chunks of code?
```suggestion
### What do we call the process of testing small chunks of code?
```

2019-02-16 12:50 UTC, oliverjam commented on QUESTIONS.md
> +### How does using TDD can help develop an application that is more secure?
```suggestion
### How can using TDD help develop an application that is more secure?
```

2019-02-18 17:07 UTC, zurda commented
This is a duplicate of: https://github.com/foundersandcoders/testing-tdd-intro/pull/3
Closing this PR since the changes are fixed in the PR linked above

2019-02-18 17:08 UTC, closed without merging